# Generated by Django 4.1 on 2022-10-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='商品图片1'),
        ),
    ]
