# Generated by Django 4.1 on 2022-10-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='活动名称')),
                ('start_time', models.CharField(max_length=20, verbose_name='活动开始时间')),
                ('end_time', models.CharField(max_length=20, verbose_name='活动结束时间')),
                ('img1', models.ImageField(upload_to='actives', verbose_name='活动图片1')),
            ],
            options={
                'verbose_name': '活动信息表',
                'verbose_name_plural': '活动信息表',
                'db_table': 't_actives',
            },
        ),
        migrations.CreateModel(
            name='ActiveGoodsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.88, verbose_name='折扣')),
                ('active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actives', to='actives.activemodel', verbose_name='活动名称')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='goods.goodsmodel', verbose_name='商品名')),
            ],
            options={
                'verbose_name': '活动商品信息表',
                'verbose_name_plural': '活动商品信息表',
                'db_table': 't_actives_goods',
            },
        ),
    ]
