# Generated by Django 4.1 on 2022-10-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activemodel',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='actives', verbose_name='活动图片1'),
        ),
    ]
