# Generated by Django 4.1 on 2022-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_phone', models.CharField(max_length=11, verbose_name='登陆手机号')),
                ('nicky_name', models.TextField(verbose_name='用户昵称')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 't_login_user',
            },
        ),
    ]
